export enum DLRequestPlatform {
  VRTMAX = 'VRTMAX',
  VTMGO = 'VTMGO',
  STREAMZ = 'STREAMZ',
  GOPLAY = 'GOPLAY',
  YOUTUBE = 'YOUTUBE',
  GENERIC_MANIFEST = 'GENERIC_MANIFEST',
  UNKNOWN = 'UNKNOWN',
}
