# This github action builds the Dockerfile and pushes the image
# to the GitHub Container Registry (ghcr.io).
# The image is tagged with the commit SHA and the latest tag.
# This action should only be triggered when changes were made to
# the dl-downer directory on the main branch.
name: Publish dl-downer

on:
  push:
    branches:
      - main
    paths:
      - 'dl-downer/**'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Convert repository owner to lowercase
        id: repoowner
        run: echo "::set-output name=lowercase::$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./dl-downer/
          push: true
          tags: |
            ghcr.io/${{ steps.repoowner.outputs.lowercase }}/${{ github.repository }}/dl-downer:${{ github.sha }}
            ghcr.io/${{ steps.repoowner.outputs.lowercase }}/${{ github.repository }}/dl-downer:latest
